name: Github actions

on:
  push:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  Build:

    name: build

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        image_tag: [old, stable]
        build_type: [Debug, Release]

    container: ghcr.io/mehdichinoune/debian-gfortran-testing:${{ matrix.image_tag }}

    steps:
    - uses: actions/checkout@v2
    - name: Preparing Data
      env:
        USERNAME: ${{ secrets.LPDAAC_USERNAME }}
        PASSWORD: ${{ secrets.LPDAAC_PASSWORD }}
      run: |
        echo machine urs.earthdata.nasa.gov >> ~/.netrc
        echo http-user="$USERNAME" >> ~/.wgetrc
        echo http-password="$PASSWORD" >> ~/.wgetrc
    - name: Configuring
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DHDF5_ROOT=/usr/local/HDF_Group/HDF5/1.12.0
    - name: Building
      run: make -C build -j$(nproc)
    - name: Running
      run: build/main