name: Github actions

on:
  push:
  schedule:
    - cron: '0 2 * * 1,4'

jobs:
  Build:

    name: build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image_tag: [old, stable, trunk]
        build_type: [Debug, Release]

    container: chinoune/debian-gfortran-testing:${{ matrix.image_tag }}

    steps:
    - uses: actions/checkout@v1
    - name: Preparing Data
      run: |
        wget https://github.com/ChinouneMehdi/PrayerTimes/releases/download/data/data.tar.xz
        tar -xvf data.tar.xz
        rm data.tar.xz
    - name: Configuring
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DHDF5_ROOT=/usr/local/HDF_Group/HDF5/1.10.6
    - name: Building
      run: make -C build -j$(nproc)
    - name: Running
      run: build/main